### ISSUE TITLE
Website scrolls sideways on mobile

### ISSUE THREAD

**Issue by amcdevitt97** [hackproductions/main-site#15]
Kinda irritating when scrolling down and the page shifts slightly to the side. I have a fix in an incoming PR

**Comment by amcdevitt97** [comment]
Also might fix issue #7 but not sure if that's all that needs done... lol

**Comment by wrussell1999** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Compress images on site](https://trello.com/c/FTPoIrc3/15-compress-images-on-site)

**Comment by wrussell1999** [comment]
Thank you @amcdevitt97!
