### ISSUE TITLE
Make site more Jekyll

### ISSUE THREAD

**Issue by wrussell1999** [hackproductions/main-site#4]
Tweak the CSS so:

- Add CSS for all Markdown features (including tables)
- We can use sass easily
- Move data to yaml files

**Comment by robzwolf** [comment]
MOAR JEKYLL 🚀

**Comment by wrussell1999** [comment]
Created some layout templates to make new pages super easy, and moved everything to sass

**Comment by wrussell1999** [comment]
Needs improvements to the _config.yml

**Comment by wrussell1999** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add more templates to the main site](https://trello.com/c/5FChHDXH/9-add-more-templates-to-the-main-site)
